modLoader = "javafml"
loaderVersion = "[@LOADER_MAJOR@,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersiveArmors/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "immersive_armors"
version = "${version}"
displayName = "Immersive Armors"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ImmersiveArmors"
authors = "Luke100000"
description = '''
    A lot of unique and vanilla-faithful armor sets.
    '''
logoFile = "logoFile.png"
itemIcon = "immersive_armors:divine_chestplate"

[[dependencies.immersive_armors]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT_VERSION@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_armors]]
modId = "forge"
mandatory = true
versionRange = "[@FORGE_VERSION@,)"
ordering = "NONE"
side = "BOTH"
